### ISSUE TITLE
Convert the compiler to Rust

### ISSUE THREAD

**Issue by mangolang** [mangolang/compiler#27]
I initially chose Kotlin for several reasons:

* It supports compiling to web (Javascript specifically).
* It is a solid language, yet extremely easy to pick up.
* I intended to very quickly rewrite in Mango itself.

But now, I want to switch to Rust:

* Kotlin is good, but Rust seems better (and more interesting). I want to see Rust grow.
* Rust can now also compile for web for most browsers (WebAssembly).
* It seems unlikely that the compiler will be rewritten in Mango early on after all, so the bigger learning time investment is acceptable.
* Although it works well in the end, I took an absurd amount of time to get Gradle for multiplatform to work, and still to change things.

**Comment by mverleg** [comment]
Progress: #28 #33

**Comment by mverleg** [comment]
Compiler isn't ready but all the Kotlin code is gone
