### ISSUE TITLE
Add a JSM+JS (in one) unit test framework

### ISSUE THREAD

**Issue by mangolang** [mangolang/compiler#4]
Most seem to be JVM-only

**Comment by mangolang** [comment]
It's not quite in one, but 

Still desirable:

- Be able to run js tests with `gradle -p mango-js test` instead of `gradle -p mango-js testJsNode`
- Have a test runner for JS - it works fine for a few tests now, but should be upgraded later

**Comment by mangolang** [comment]
Kluent seems interesting

**Comment by mverleg** [comment]
Placeholder tests (and a few real ones) are in place. They need to run automatically and need to be a precondition for merging.

**Comment by mverleg** [comment]
It looks like Javascript tests are also being run!

Inspiration from https://github.com/exercism/kotlin/blob/master/.travis.yml

**Comment by mverleg** [comment]
Testing infrastructure added in various commits, completed in a48ede93ba047003b569569a305b3f740c9f1a24.
