### ISSUE TITLE
Add static analysis to protect code quality

### ISSUE THREAD

**Issue by mangolang** [mangolang/compiler#5]
This one seems promosing: https://github.com/arturbosch/detekt

**Comment by mangolang** [comment]
This one seems useful to enforce Kotlin official style guide, but possibly a subset of Detekt since this one is limited to that style guide. https://github.com/shyiko/ktlint

**Comment by mverleg** [comment]
It's working (as part of Gradle build), but configuration is ignored.

**Comment by mverleg** [comment]
Implemented in 260b740ba8ce2d91791672116eb971d3a1036dc4

**Comment by mverleg** [comment]
#23

**Comment by mverleg** [comment]
https://github.com/jeremymailen/kotlinter-gradle -> Only get the lint task on JVM projects, and it's too much of a hacky mess to include all sources from there.
https://github.com/JLLeitschuh/ktlint-gradle -> Creates the task but cannot run it with check ([issue](https://github.com/JLLeitschuh/ktlint-gradle/issues/55)). It's also slow and doesn't stop on error (ignores config?).

**Comment by mverleg** [comment]
ktlint-gradle only works for JVM platform atm (issue58 in the repo)

**Comment by mverleg** [comment]
Switched to cargo format, which now works and is enforced locally (there is some kind of version mismatch between local and Travis, so it had to be turned off on Travis for now since it kept flagging things that weren't being fixed by ``cargo +nightly fmt`; it'll be turned on again later).
